---
title: "mpn_exploration_notebook"
format: html
---

Listing all the folders, recursive shows empty subfolder name
```{r}
list.dirs(path = here::here("data"), 
          full.names = FALSE,
          recursive = TRUE)

```

Tracking down empty subfolder name
```{r}

for (x in list.dirs(path = here::here("data/"), 
          full.names = TRUE,
          recursive = FALSE)) {
  
  subfolder = list.dirs(path = x, 
          full.names = FALSE,
          recursive = FALSE)


  if(length(subfolder) > 0) {print(x)}
  
}

```

```{r}
x= here::here("data/MPN 0060/")

subfolder = list.dirs(path = x, 
          full.names = FALSE,
          recursive = FALSE)

if(length(subfolder) > 0) {print(x)}
```

Listing files within mpn 0060 folder
```{r}
list.files(path = here::here("data/MPN 0060"))
```

Listing files within folders
```{r}
df_files = c()
for (x in list.dirs(path = here::here("data/"), 
          full.names = TRUE,
          recursive = FALSE)) {
  
  subfiles = list.files(path = x, 
          full.names = FALSE,
          recursive = FALSE)
  df_files = c(df_files, subfiles)
  
}

```


df_files is now a character vector with all file names. next step is figure out how many file names
contain the word geocode. stringr package